services:
  db:
    image: postgres:latest
    container_name: boulder-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: boulder-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
